language: python

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"

install:
  - pip install pybuilder
  - pyb install_dependencies --verbose

script:
  - pyb --verbose

notifications:
  email:
    - diego.costantini@gmail.com
